<?php echo $this->doctype().PHP_EOL; ?>
<head>
	<!-- Meta -->
	<?php $this->headTitle()->setSeparator (' - '); ?>
	<?php $this->headTitle('Mon site'); ?>
	<?php echo $this->headTitle(). PHP_EOL;
	
	 $this->headLink()->appendStylesheet('/css/reset.css','all');
	 $this->headLink()->appendStylesheet('/css/font.css','all');	
	 $this->headLink()->appendStylesheet('/css/style.css','all');
	 echo $this->headLink(). PHP_EOL;

	 $this->headScript()->appendFile('/js/less-grid-4.js','text/javascript');
	 echo $this->headScript(). PHP_EOL;
	 
	 // $this->headMeta()->setHttpEquiv();
	 echo $this->headMeta();
	 
	?>
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>


